version: '3.5'

services:
  # https://hub.docker.com/_/mariadb?tab=tags
  mariadb105:
    image: mariadb:10.5
    container_name: mariadb105
    restart: unless-stopped
    tty: true
    ports:
      - 3315:3306
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      SERVICE_NAME: mariadb105
    volumes:
      - ~/.docker-conf/mariadb_10.5:/var/lib/mysql/

# networks:
#   net-1:
#     driver: bridge

# volumes:
#   mariadb105:
#     driver: local
