version: '3.5'

services:
  # https://hub.docker.com/_/mysql?tab=tags
  mysql8:
    image: mysql:8.0.29
    container_name: mysql8
    restart: unless-stopped
    tty: true
    command: --sql_mode=''
    ports:
      - 3306:3306
    environment:
      # MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      SERVICE_NAME: mysql8
    volumes:
      - ~/.docker-conf/mysql_8:/var/lib/mysql/

# networks:
#   net-1:
#     driver: bridge

# volumes:
#   mysql8:
#     driver: local
