version: '3.5'

services:
  # https://hub.docker.com/_/adminer?tab=tags
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    # links: 
    #   - mysql5
    # depends_on:
    #   - mysql5
  
# networks:
#   net-1:
#     driver: bridge
