version: '3.5'

services:
  # https://hub.docker.com/_/adminer?tab=tags
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8081:8080
    # links: 
    #   - mysql5
    # depends_on:
    #   - mysql5
  
  # https://hub.docker.com/_/phpmyadmin?tab=tags
  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: unless-stopped
  #   ports:
  #     - 8082:80
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
    # links: 
    #   - mysql5
    # depends_on:
    #   - mysql5

  # https://hub.docker.com/_/mysql?tab=tags
  mysql5:
    image: mysql:5.7.38
    container_name: mysql5
    restart: unless-stopped
    tty: true
    command: 
      --sql_mode=''
    ports:
      - 3357:3306
    environment:
      # MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      SERVICE_NAME: mysql5
    volumes:
      # - ./mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ~/.docker-conf/mysql_5.7.38:/var/lib/mysql/

  # https://hub.docker.com/_/mysql?tab=tags
  mysql8:
    image: mysql:8.0.21
    container_name: mysql8
    restart: unless-stopped
    tty: true
    command: --sql_mode=''
    ports:
      - 3380:3306
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      SERVICE_NAME: mysql8
    volumes:
      - ~/.docker-conf/mysql_8:/var/lib/mysql/

  # https://hub.docker.com/_/mariadb?tab=tags
  mariadb101:
    image: mariadb:10.1
    container_name: mariadb101
    restart: unless-stopped
    tty: true
    ports:
      - 3311:3306
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      SERVICE_NAME: mariadb101
    volumes:
      - ~/.docker-conf/mariadb_10.1:/var/lib/mysql/

  # https://hub.docker.com/_/mariadb?tab=tags
  mariadb103:
    image: mariadb:10.3
    container_name: mariadb103
    restart: unless-stopped
    tty: true
    ports:
      - 3313:3306
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      SERVICE_NAME: mariadb103
    volumes:
      - ~/.docker-conf/mariadb_10.3:/var/lib/mysql/

  # https://hub.docker.com/_/mariadb?tab=tags
  mariadb105:
    image: mariadb:10.5
    container_name: mariadb105
    restart: unless-stopped
    tty: true
    ports:
      - 3315:3306
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      SERVICE_NAME: mariadb105
    volumes:
      - ~/.docker-conf/mariadb_10.5:/var/lib/mysql/

# networks:
#   net-1:
#     driver: bridge

# volumes:
#   mysql5:
#     driver: local
#   mysql8:
#     driver: local
#   mariadb101:
#     driver: local
#   mariadb103:
#     driver: local
#   mariadb105:
#     driver: local
