version: '3.5'

services:
  # https://hub.docker.com/_/mariadb?tab=tags
  mariadb101:
    image: mariadb:10.1
    container_name: mariadb101
    restart: unless-stopped
    tty: true
    ports:
      - 3311:3306
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      SERVICE_NAME: mariadb101
    volumes:
      - ~/.docker-conf/mariadb_10.1:/var/lib/mysql/

# networks:
#   net-1:
#     driver: bridge

# volumes:
#   mariadb101:
#     driver: local
