version: '3'

services:

  mongodb:
    image: mongo:5.0

    container_name: 'mongodb'

    ports:
      - 27017:27017

    volumes:
      - ~/.docker-conf/mongo:/data/db

    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

    networks:
      - network


  # mongo-express:
  #   image: mongo-express

  #   container_name: 'mongo-express'

  #   restart: always

  #   ports:
  #     - 8081:8081

  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: admin
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: admin
  #     ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/

  #  networks:
  #    - network

  
networks:
  network: {}
