version: '3.5'

services:
  adminer:
    image: adminer
    restart: unless-stopped
    tty: true
    ports:
      - 8081:8080

  # mysql -u root -p -h 172.17.0.1 -P 3357
  # 172.17.0.1:3357
  mysql5:
    image: mysql:5.7
    container_name: mysql5
    restart: unless-stopped
    tty: true
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0 --sql_mode=''
    ports:
      - 3357:3306
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql5
    volumes:
      - ./mysql5:/var/lib/mysql/

  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    restart: unless-stopped
    tty: true
    ports:
      - 8080:80
      - 444:443
    environment:
      SERVICE_NAME: php-apache
      SERVICE_TAGS: dev
    working_dir: /var/www/html/
    volumes:
      - ./html/:/var/www/html/
