version: '3.5'

services:  
  # https://hub.docker.com/_/phpmyadmin?tab=tags
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    links: 
      - mysql5
    depends_on:
      - mysql5

# networks:
#   net-1:
#     driver: bridge
