version: '3.5'

services:
  # https://hub.docker.com/_/mariadb?tab=tags
  mariadb103:
    image: mariadb:10.3
    container_name: mariadb103
    restart: unless-stopped
    tty: true
    ports:
      - 3313:3306
    environment:
      MYSQL_DATABASE: distr
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      SERVICE_NAME: mariadb103
    volumes:
      - ~/.docker-conf/mariadb_10.3:/var/lib/mysql/

# networks:
#   net-1:
#     driver: bridge

# volumes:
#   mariadb103:
#     driver: local
